@startuml ActorsAndTransactions
agent "Scheduling Client" as Client
agent "Scheduling Server" as Server
Client -- Server : "Find Appointment [ITI-Y1] ↓"
Client -- Server : "Pre-fetch Slots [ITI-Y2] ↓"
Client -- Server : "Hold Appointment [ITI-Y3] ↓"
Client -- Server : "Book Appointment [ITI-Y4] ↓"
@enduml

