@startuml findappointments-processflow
skinparam svgDimensionStyle false
hide footbox
participant "Scheduling Client" as Client
participant "Scheduling Server" as Server
note left of Client
Pre-requisite: 
Patient identification
already completed
end note
activate "Client"
"Client" -> "Server" : 1. Find Potential Appointments Query
activate "Server"
"Server" --> "Client" : 2. Find Potential Appointments Response
deactivate "Server"
deactivate "Client"
@enduml
