@startuml
skinparam responseMessageBelowArrow true
skinparam svgDimensionStyle false
hide footbox

actor "Dr. Brown" as User #FFFFFF
participant "Clinical Information Systen \n (Scheduling Client)" as RequestingActor
participant "Scheduling Server \n" as RespondingActor

autonumber 1 1 "<b>[00]"

activate "RequestingActor"
User --> RequestingActor: Open view

|||
RequestingActor -> RespondingActor: Find Appointments Query Request [ITI-Y1]
activate "RespondingActor"
RespondingActor --> RequestingActor: Find Appointments Query Response [ITI-Y1]
deactivate "RespondingActor"

|||
User --> RequestingActor: Select Appointment
User --> RequestingActor: Add additional data
User --> RequestingActor: Confirm booking

|||
RequestingActor -> RespondingActor: Book Appointment Request [ITI-Y3]
activate "RespondingActor"
RespondingActor --> RequestingActor: Book Appointment Response [ITI-Y3]
deactivate "RespondingActor"

autonumber stop

@enduml
