@startuml
skinparam responseMessageBelowArrow true
skinparam svgDimensionStyle false
hide footbox

actor "Dr. Brown" as User #FFFFFF
participant "Clinical Information Systen \n (Scheduling Client)" as RequestingActor
participant "Scheduling Server \n" as RespondingActor

autonumber 1 1 "<b>[00]"

activate "RequestingActor"
User --> RequestingActor: Open view

|||
RequestingActor -> RespondingActor: Find Existing Appointments Query Request [ITI-117]
activate "RespondingActor"
RespondingActor --> RequestingActor: Find Existing Appointments Query Response [ITI-117]
deactivate "RespondingActor"

|||
RequestingActor -> RespondingActor: Find Potential Appointments Query Request [ITI-114]
activate "RespondingActor"
RespondingActor --> RequestingActor: Find Potential Appointments Query Response [ITI-114]
deactivate "RespondingActor"

|||
User --> RequestingActor: Select Appointment
User --> RequestingActor: Add additional data
User --> RequestingActor: Confirm booking

|||
RequestingActor -> RespondingActor: Book Appointment Request [ITI-116]
activate "RespondingActor"
RespondingActor --> RequestingActor: Book Appointment Response [ITI-116]
deactivate "RespondingActor"

autonumber stop

@enduml
