@startuml
skinparam responseMessageBelowArrow true
skinparam svgDimensionStyle false
hide footbox

actor "Hospital User" as User #FFFFFF
participant "Hospital Discharge Systen \n (Scheduling Client)" as RequestingActor
participant "Practice Scheduling System \n (Scheduling Server)" as RespondingActor

autonumber 1 1 "<b>[00]"

activate "RequestingActor"
User --> RequestingActor: Open view

|||
RequestingActor -> RespondingActor: Find Potential Appointments Query Request [ITI-115]
activate "RespondingActor"
RespondingActor --> RequestingActor: Find Potential Appointments Query Response [ITI-115]
deactivate "RespondingActor"

|||
User --> RequestingActor: Select Appointment
User --> RequestingActor: Add additional data
User --> RequestingActor: Confirm booking

|||
RequestingActor -> RespondingActor: Book Appointment Request [ITI-117]
activate "RespondingActor"
RespondingActor --> RequestingActor: Book Appointment Response [ITI-117]
deactivate "RespondingActor"

autonumber stop

@enduml
