# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.scheduling
canonical: https://profiles.ihe.net/ITI/Scheduling
version: 1.0.0
name: IHE_ITI_Scheduling
title: "Scheduling"
description: The IHE FHIR Scheduling Profile is a specification providing FHIR APIs and guidance for access to and booking of appointments for patients by both patient and practitioner end users. This specification is based on FHIR Version 4 and specifically the Schedule, Slot, and Appointment resources, and on the previous work of the [Argonaut Project](https://fhir.org/guides/argonaut/scheduling/release1/).
#releaseLabel: ci-build
#releaseLabel: ballot
releaseLabel: Trial-Implementation
date: 2024-12-12
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-4.0
fhirVersion: 4.0.1
dependencies: 
#  hl7.fhir.uv.ipa: 1.0.0
  ihe.iti.balp:
    id: iheitibasicaudit
    uri: https://profiles.ihe.net/ITI/BALP/ImplementationGuide/ihe.iti.balp
    version: 1.1.x
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
#copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2024+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

#resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true
resources:
  Bundle/example-appt-bundle-1:
    name: Potential Appointment List 
    description: Response to a $find operation example
    exampleBoolean: true
  Practitioner/dr-y:
    name: Practitioner Dr. Y
    description: Example practitioner
    exampleBoolean: true
  Appointment/appt1-1:
    name: Example appointment with Dr. Y
    description: Example appointment
    exampleBoolean: true
  Patient/pat1:
    name: Meiko Lufhir Jr., PhD
    description: Example patient
    exampleBoolean: true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: Scheduling Home
    generation: markdown
  volume-1.md:
    title: 1:55 Scheduling
    generation: markdown
  ITI-115.md:
    title: 2:3.115 Find Potential Appointments [ITI-115]
    generation: markdown
  ITI-116.md:
    title: 2:3.116 Hold Appointment [ITI-116]
    generation: markdown
  ITI-117.md:
    title: 2:3.117 Book Appointment [ITI-117]
    generation: markdown
  ITI-118.md:
    title: 2:3.118 Find Existing Appointments [ITI-118]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  other.md:
    title: Changes to Other IHE Specifications
    generation: markdown
  download.md:
    title: Download and Analysis
    generation: markdown
  issues.md:
    title: Significant Changes and Issues
    generation: markdown

menu:
  Scheduling Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#actors-and-transactions
    Actor Options: volume-1.html#actor-options
    Required Actor Groupings: volume-1.html#required-groupings
    Overview: volume-1.html#overview
    Security Considerations: volume-1.html#security-considerations
    Cross-Profile Considerations: volume-1.html#other-grouping
  Volume 2:
    Find Potential Appointments [ITI-115]: ITI-115.html
    Hold Appointment [ITI-116]: ITI-116.html
    Book Appointment [ITI-117]: ITI-117.html
    Find Existing Appointments [ITI-118]: ITI-118.html
  Artifacts: artifacts.html
  Other:
    Changes to Other IHE Specifications: other.html
    Download and Analysis: download.html
    Test Plan: testplan.html