# sushi-config.yaml is documented https://fshschool.org/docs/sushi/configuration/
# ───────────────────────────────────────────────────
# the id should be lowercase made up of "ihe." + {domain acronym} + "." + {profile acronym/short-name}
# e.g. ihe.iti.mhds, or ihe.iti.basicaudit
id: ihe.iti.scheduling
canonical: https://profiles.ihe.net/ITI/Scheduling
version: 0.1.0-current
name: IHE_ITI_Scheduling
title: "IHE ITI Scheduling"
description: put the short description of the profile here. it should explain what problem is being solved
releaseLabel: ci-build
#releaseLabel: Trial-Implementation
#date: 2022-01-02
status: active
publisher:
  - name: IHE IT Infrastructure Technical Committee
  - url: https://www.ihe.net/ihe_domains/it_infrastructure/
  - email: iti@ihe.net
contact:
  - name: IHE IT Infrastructure Technical Committee
    telecom:
      - system: email
        value: iti@ihe.net
license:  CC-BY-SA-4.0
fhirVersion: 4.0.1
dependencies: 
  hl7.fhir.uv.ipa: 1.0.0
jurisdiction: 'http://unstats.un.org/unsd/methods/m49/m49.htm#001'
copyright: IHE http://www.ihe.net/Governance/#Intellectual_Property
copyrightYear: 2022+


parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
    - input/examples
#  path-pages:
#    - input/pagecontent
#    - fsh-generated/includes
  show-inherited-invariants: 'false'
  usage-stats-opt-out: 'false'
  logging: progress
  shownav: 'true'
  active-tables: 'false'
  apply-contact: 'true'
  apply-jurisdiction: 'true'
  apply-publisher: 'true'
  apply-version: 'true'

resources:
# list every example here with a name, description and that exampleBoolean is true; These are used to populate the artifacts page, and are needed to eliminate build warnings 
# You may delay filling out this section until you approach publication as it is merely a nice to have and eliminates build warnings -- If you do this then you will need above the autoload-resources true


pages:
# itemize here each narrative page. Include assigned section numbers when appropriate
  index.md:
    title: 1:55. Profile Home
    generation: markdown
  volume-1.md:
    title: 1:55. Profile Volume 1
    generation: markdown
  ITI-115.md:
    title: 2:3.115 Transaction one [ITI-115]
    generation: markdown
  ITI-116.md:
    title: 2:3.116 Transaction two [ITI-116]
    generation: markdown
  ITI-117.md:
    title: 2:3.117 Transaction three [ITI-117]
    generation: markdown
  ITI-118.md:
    title: 2:3.118 Transaction three [ITI-118]
    generation: markdown
  testplan.md:
    title: "Test Plan"
    generation: markdown
  issues.md:
    title: Open and Closed issues
    generation: markdown

menu:
  FHIR Scheduling Home: index.html
  Volume 1:
    Introduction: volume-1.html
    Actors and Transactions: volume-1.html#1551-fhir-scheduling-actors-and-transactions--
    Actor Options: volume-1.html#552-scheduling-actor-options--
    Required Groupings: volume-1.html#553-scheduling-required-actor-groupings--
    Overview: volume-1.html#554-fhir-scheduling-overview--
    Security Considerations: volume-1.html#555-fhir-scheduling-security-considerations--
    Cross-Profile Considerations: volume-1.html#556-fhir-scheduling-cross-profile-considerations--
  Volume 2:
    Find Appointments [ITI-115]: ITI-115.html
    Hold Appointment [ITI-116]: ITI-116.html
    Book Appointment [ITI-117]: ITI-117.html
  Test Plan: testplan.html
  Artifacts: artifacts.html
